version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: meter-readings-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-MeterReadings}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - meter_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meter-readings-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://[::]:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MeterReadings;Username=postgres;Password=postgres
    ports:
      - "${API_PORT:-8000}:80"
    volumes:
      - ./backend/MeterReadings.API/Data:/app/Data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - meter_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meter-readings-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - api
    networks:
      - meter_network
      
volumes:
  postgres_data:

networks:
  meter_network:
    driver: bridge